const colors = {
    white: "#FFF",
    black: '#000',
    lightGrey: "#CCC",
    verdunGreen: "#375A04",
    saddleBrown: "#944317",
    altGreen: "#1D7F11FA",
    harleyDavidsonOrange: "#DF290C",
    sun: "#FA923F",
    red: "#FF0000",
    whisper: '#EEE',
    solitude: '#E9EDF0',
    pattensBlue: '#C0DDF5',
    nightRider: '#333333',
    westSide : '#F08238',
    atomicTangerine: '#FFA263',
    nevada: '#636767',
    silver: '195, 195, 195'
}

const dict = {
    home: 'Home',
    edit: 'Edit',
    delete: 'Delete',
    clear: 'Clear',
    submit: 'Submit',
    back: 'Go back',
    products: 'Products',
    color: 'Color',
    stones: 'Stones',
    category: 'Category',
    quantity: 'Quantity',
    karats: 'Karats',
    costEuro: 'Cost in euro',
    costDollars: 'Cost in dollars',
    silverWeight: 'Silver weight',
    producerCode: 'Producer Code',
    goldWeight: 'Gold weight',
    description: 'Description',
    newProducts: 'New Products',
    history: 'History',
    categories: 'Categories',
    time: 'Time',
    stoneWeight: 'Stone weight',
    productID: 'Product ID',
    pageNotFound: 'The page you were trying to get was not found',
    unexpectedError: 'Something went wrong!',
    addNewProduct: 'Add new product',
    selectProduct: 'Please select a Post!',
    errorUponProductAddition: 'Something went wrong adding that product!',
    errorUponProductDeletion: 'Something went wrong deleting that product!',
    successfulProductAddition: 'Product added successfully!',
    successfulProductDeletion: 'Product deleted successfully!',
    categoriesNotFound: 'Didn\'t find any categories',
    productsNotFound: 'Didn\'t find any products',
    productNotExist: 'Sorry, the product does not exist.'
}

export {colors, dict};