const colors = {
    white: "#FFF",
    black: '#000',
    blackAlt: '0, 0, 0',
    lightGrey: "#CCC",
    verdunGreen: "#375A04",
    saddleBrown: "#944317",
    altGreen: "#1D7F11FA",
    harleyDavidsonOrange: "#DF290C",
    sun: "#FA923F",
    red: "#FF0000",
    cinnabar: "#E53E3E",
    whisper: '#EEE',
    solitude: '#E9EDF0',
    pattensBlue: '#C0DDF5',
    nightRider: '#333333',
    westSide : '#F08238',
    atomicTangerine: '#FFA263',
    nevada: '#636767',
    silver: '195, 195, 195',
    neonBlue: '#5C5CFB',
    curiousBlue: '#3182CE',
    persianBlue: '#2424AE',
}

const dict = {
    home: 'Home',
    edit: 'Edit',
    delete: 'Delete',
    clear: 'Clear',
    submit: 'Submit',
    back: 'Go back',
    products: 'Products',
    stores: 'Stores',
    color: 'Color',
    stones: 'Stones',
    category: 'Category',
    quantity: 'Quantity',
    karats: 'Karats',
    costEuro: 'Cost in euro',
    costDollars: 'Cost in dollars',
    diamondWeight: 'Diamond weight',
    silverWeight: 'Silver weight',
    producerCode: 'Producer Code',
    goldWeight: 'Gold weight',
    description: 'Description',
    newProducts: 'New Products',
    history: 'History',
    categories: 'Categories',
    time: 'Time',
    add: 'Add',
    yes: 'Yes',
    no: 'No',
    disable: 'Disable',
    store: 'Store',
    noStock: 'Out of stock',
    stoneWeight: 'Stone weight',
    productCode: 'Product Code',
    pageNotFound: 'The page you were trying to get was not found',
    unexpectedError: 'Something went wrong!',
    addNewProduct: 'Add new product',
    addNewCategory: 'Add new category',
    selectProduct: 'Please select a Post!',
    pageNotExist: 'This page does not exist',
    categoryNotFound: 'Category Not Found',
    errorUponProductAddition: 'Something went wrong adding that product!',
    errorUponCategoryAddition: 'Something went wrong adding that category!',
    errorUponCategoryUpdate: 'Something went wrong updating that category!',
    errorUponProductDeletion: 'Something went wrong deleting that product!',
    errorUponCategoryDeletion: 'Something went wrong deleting that category!',
    productDisableMessage: 'Are you sure you want to disable this product?',
    productDeleteMessage: 'Are you sure you want to delete this product?',
    categoryDeletionMessage: 'Are you sure you want to delete this category?',
    successfulProductAddition: 'Product added successfully!',
    successfulProductDeletion: 'Product deleted successfully!',
    successfulCategoryAddition: 'Category added successfully!',
    successfulCategoryUpdate: 'Category updated successfully!',
    successfulCategoryDeletion: 'Category deleted successfully!',
    categoryAlreadyExists: 'Category Already Exists',
    categoriesNotFound: 'Didn\'t find any categories',
    productsNotFound: 'Didn\'t find any products',
    storesNotFound: 'Didn\'t find any stores',
    productNotExist: 'Sorry, the product does not exist.'
}

export {colors, dict};