const newProductActionTypes = {
    ADD_PRODUCT_START: 'ADD_PRODUCT_START',
    ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_FAILED: 'ADD_PRODUCT_FAILED',

    UPDATE_PRODUCT_START: 'UPDATE_PRODUCT_START',
    UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_FAILED: 'UPDATE_PRODUCT_FAILED',

    PAGE_UNLOADED: 'PAGE_UNLOADED',

    IMAGE_UPLOAD_START: 'IMAGE_UPLOAD_START',
    IMAGE_UPLOAD_SUCCESS: 'IMAGE_UPLOAD_SUCCESS',
    IMAGE_UPLOAD_FAILED: 'IMAGE_UPLOAD_FAILED',

    EDIT_PRODUCT: 'EDIT_PRODUCT',
    VALIDATION_HANDLER: 'VALIDATION_HANDLER',
    POPULATE_SELECT_FIELDS: 'POPULATE_SELECT_FIELDS',
    IMAGE_UPLOAD_PROPERTIES: 'IMAGE_UPLOAD_PROPERTIES',
    CLEAR_NEW_PRODUCT: 'CLEAR_NEW_PRODUCT'
}

export default newProductActionTypes;