const ProducerActionTypes = {
    FETCH_PRODUCERS_START: 'FETCH_PRODUCERS_START',
    FETCH_PRODUCERS_SUCCESS: 'FETCH_PRODUCERS_SUCCESS',
    FETCH_PRODUCERS_FAILED: 'FETCH_PRODUCERS_FAILED',
    
    FETCH_SINGLE_PRODUCER_START: 'FETCH_SINGLE_PRODUCER_START',
    FETCH_SINGLE_PRODUCER_SUCCESS: 'FETCH_SINGLE_PRODUCER_SUCCESS',
    FETCH_SINGLE_PRODUCER_FAILED: 'FETCH_SINGLE_PRODUCER_FAILED',

    DELETE_PRODUCER_START: 'DELETE_PRODUCER_START',
    DELETE_PRODUCER_SUCCESS: 'DELETE_PRODUCER_SUCCESS',
    DELETE_PRODUCER_FAILED: 'DELETE_PRODUCER_FAILED',

    ADD_PRODUCER_START: 'ADD_PRODUCER_START',
    ADD_PRODUCER_SUCCESS: 'ADD_PRODUCER_SUCCESS',
    ADD_PRODUCER_FAILED: 'ADD_PRODUCER_FAILED',

    UPDATE_PRODUCER_START: 'UPDATE_PRODUCER_START',
    UPDATE_PRODUCER_SUCCESS: 'UPDATE_PRODUCER_SUCCESS',
    UPDATE_PRODUCER_FAILED: 'UPDATE_PRODUCER_FAILED',
}

export default ProducerActionTypes;