const productActionTypes = {
    FETCH_PRODUCTS_START: 'FETCH_PRODUCTS_START',
    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_FAILED: 'FETCH_PRODUCTS_FAILED',

    SET_PRODUCTS: 'SET_PRODUCTS',

    FETCH_SINGLE_PRODUCT_START: 'FETCH_SINGLE_PRODUCT_START',
    FETCH_SINGLE_PRODUCT_SUCCESS: 'FETCH_SINGLE_PRODUCT_SUCCESS',
    FETCH_SINGLE_PRODUCT_FAILED: 'FETCH_SINGLE_PRODUCT_FAILED',

    DELETE_PRODUCT_START: 'DELETE_PRODUCT_START',
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAILED: 'DELETE_PRODUCT_FAILED',

    ADD_PRODUCT_START: 'ADD_PRODUCT_START',
    ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_FAILED: 'ADD_PRODUCT_FAILED',
    
    SELECT_PRODUCT_ID: 'SELECT_PRODUCT_ID',

    FETCH_HISTORY_START: 'FETCH_HISTORY_START',
    FETCH_HISTORY_SUCCESS: 'FETCH_HISTORY_SUCCESS',
    FETCH_HISTORY_FAILED: 'FETCH_HISTORY_FAILED',
    
}

export default productActionTypes;